#
# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#

[workspace]
members = [
    "cda",
    "common",
    "fms",
    "powertrain",
    "vehicle-properties",
]
resolver = "2"

[workspace.package]
readme = "README.md"
repository = "git@github.com:eclipse-sdv-blueprints/commercial-sdv-stack"
version = "0.1.0-SNAPSHOT"
edition = "2024"

[workspace.dependencies]
async-trait = { version = "0.1.92" }
backon = { version = "1.6.0", default-features = false, features = ["tokio-sleep"] }
clap = { version = "4.6.7", default-features = false }
common = { path = "common", default-features = false }
env_logger = { version = "0.11.11", default-features = false, features = [
    "humantime",
] }
log = { version = "0.4.34" }
regorus = { version = "0.12.0" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151" }
spiffe = { version = "0.16.1", default-features = false }
# tokio does not enable features by default
tokio = { version = "1.53.1" }
tracing = { version = "0.1.44", default-features = false }
tracing-subscriber = { version = "0.3.23", default-features = false }
up-rust = { version = "0.9.0", default-features = false }
up-transport-mqtt5 = { version = "0.4.0" }
up-transport-zenoh = { version = "0.9.1" }

[profile.release]
lto = true          # Link time optimization (dead code removal etc...)
opt-level = "s"
codegen-units = 1
incremental = false
strip = true

[patch.crates-io]
# Necessary because upstream is still using an older version of serde_qs (0.14 instead of 1.0.0-rc.3)
aide = { git = "https://github.com/alexmohr/aide.git", rev = "56355cb" }
doip-codec = { git = "https://github.com/theswiftfox/doip-codec.git", rev = "0dba319" }
doip-definitions = { git = "https://github.com/theswiftfox/doip-definitions.git", rev = "bdeab8c" }
flatbuffers = { git = "https://github.com/alexmohr/flatbuffers.git", rev = "0ba3307d" }
