#
# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#

networks:
  backend:
    driver: bridge
    attachable: true
  vehicle-uprotocol:
    driver: bridge
    attachable: true
  vehicle-sovd:
    driver: bridge
    attachable: true

volumes:
  mosquitto-data:
  mosquitto-logs:
  spire-agent-socket:

configs:
  trust-store:
    file: ./config/spire/certs/trusted-certs.pem

services:
  dozzle: # https://dozzle.dev/guide/what-is-dozzle
    image: amir20/dozzle:latest
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    ports:
      - "127.0.0.1:8080:8080"

  # BACKEND SERVICES

  spire-server:
    image: ghcr.io/spiffe/spire-server:1.15.3
    # user as recommended at https://github.com/spiffe/spire/blob/main/doc/docker_images.md
    user: "1000:1000"
    networks:
      - backend
      - vehicle-uprotocol
    ports:
      - 8081
    configs:
      - source: trust-store
        target: /etc/spire/server/trusted-certs.pem
    volumes:
      - ./config/spire/certs/ca-cert.pem:/etc/spire/server/ca-cert.pem:ro
      - ./config/spire/certs/ca-key.pem:/etc/spire/server/ca-key.pem:ro
      - ./config/spire/server/server.conf:/etc/spire/server/server.conf:ro
    command: ["-config", "/etc/spire/server/server.conf"]
    restart: unless-stopped

  spire-agent:
    image: ghcr.io/spiffe/spire-agent:1.15.3
    pid: "host"
    networks:
      - backend
      - vehicle-uprotocol
    depends_on:
      - spire-server
    configs:
      - source: trust-store
        target: /etc/spire/agent/trusted-certs.pem
    volumes:
      - ./config/spire/certs/spire-agent-cert.pem:/etc/spire/agent/cert.pem:ro
      - ./config/spire/certs/spire-agent-key.pem:/etc/spire/agent/key.pem:ro
      - ./config/spire/agent/agent.conf:/etc/spire/agent/agent.conf:ro
      # the following is needed to allow other containers to talk
      # to the agent's  Workload API (via UNIX domain socket)
      - type: volume
        source: spire-agent-socket
        target: /run/spire/agent/public
        read_only: false
      # the following is needed for the Spire Agent to be able to attest
      # Docker container workloads
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    command: ["-config", "/etc/spire/agent/agent.conf"]
    restart: unless-stopped

  symphony-api:
    profiles:
      - fw-update
    image: ghcr.io/eclipse-symphony/symphony-api:0.48.48
    networks:
      - backend
    ports:
      - "127.0.0.1:8082:8082"
    environment:
      - USE_SERVICE_ACCOUNT_TOKENS=false
      - SYMPHONY_API_URL=http://localhost:8082/v1alpha2/
      - CONFIG=/symphony-api-no-k8s.json
      - LOG_LEVEL=Error
    restart: unless-stopped
  symphony-portal:
    profiles:
      - fw-update
    image: ghcr.io/eclipse-symphony/symphony-portal:0.48-proxy.40
    networks:
      - backend
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - SYMPHONY_API=http://symphony-api:8082/v1alpha2/
      - NEXTAUTH_SECRET=SymphonyKey
      - NEXTAUTH_URL=http://localhost:3000
    restart: unless-stopped
    depends_on:
      - symphony-api
  mosquitto:
    image: eclipse-mosquitto:2
    networks:
      - backend
      - vehicle-uprotocol
    ports:
      - "127.0.0.1:1883:1883"
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mosquitto_sub -h localhost -p 1883 -i healthcheck -t '$$SYS/#' -C 1 -W 3 >/dev/null 2>&1 || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  fms:
    profiles:
      - powertrain
      - properties
    image: ghcr.io/eclipse-sdv-blueprints/commercial-sdv-stack/fms:latest
    build:
      context: ./uservices
      dockerfile: ./fms/Dockerfile
    container_name: fms
    networks:
      - backend
    environment:
      - UP_LOCAL_ADDRESS=up://backend/103AA/1/0
      - RUST_LOG=info,fms=debug
      - MQTT_BROKER_URI=mqtt://mosquitto:1883
      - MQTT_CLIENT_ID=fleet-management-system
      - SPIFFE_ENDPOINT_SOCKET=unix:/tmp/spire-agent/public/api.sock
    depends_on:
      mosquitto:
        condition: service_healthy
    volumes:
      # the following is needed to talk to the SPIRE Agent's Workload API (via UNIX domain socket)
      - type: volume
        source: spire-agent-socket
        target: /tmp/spire-agent/public
        read_only: false
    command: ["mqtt5"]

  # IN-VEHICLE SERVICES

  symphony-agent:
    profiles:
      - fw-update
    image: ghcr.io/eclipse-symphony/symphony-api:0.48.48
    networks:
      - vehicle-uprotocol
    volumes:
      - ./config/symphony/symphony-agent.json:/symphony-agent.json:ro
    environment:
      - CONFIG=/symphony-agent.json
      - LOG_LEVEL=info
      - RUST_LOG=INFO,uprotocol=INFO
    restart: unless-stopped
  ecu-updater:
    profiles:
      - fw-update
    image: ghcr.io/eclipse-uprotocol/symphony-target-example-rust/ecu-updater:0.1.1
    build: https://github.com/eclipse-uprotocol/symphony-target-example-rust.git#76e508eaa44829aa52ab7451eefa08bf87c1750e
    command: ["mqtt5"]
    networks:
      - vehicle-uprotocol
    environment:
      - UP_LOCAL_ADDRESS=up://vehicle/1A100/1/0
      - MQTT_BROKER_URI=mqtt://mosquitto:1883
      - MQTT_CLIENT_ID=ecu-updater
      - RUST_LOG=info,up_rust::symphony=debug
    depends_on:
      - mosquitto
  databroker:
    image: "ghcr.io/eclipse-kuksa/kuksa-databroker:0.6.1"
    networks:
      - vehicle-uprotocol
    ports:
      - "127.0.0.1:55555:55555"
    volumes:
      - "./config/databroker/vss_vehicle_info.json:/vss_vehicle_info.json:ro"
    environment:
      KUKSA_DATABROKER_ADDR: "0.0.0.0"
      KUKSA_DATABROKER_PORT: "55555"
      KUKSA_DATABROKER_METADATA_FILE: "/vss_vehicle_info.json"
      RUST_LOG: "info"
    # for the time being, we do not use TLS secured connections to Databroker
    command: "--insecure"
  vehicle-properties:
    profiles:
      - properties
    image: ghcr.io/eclipse-sdv-blueprints/commercial-sdv-stack/vehicle-properties:latest
    build:
      context: ./uservices
      dockerfile: ./vehicle-properties/Dockerfile
    container_name: vehicle-properties
    networks:
      - vehicle-uprotocol
    environment:
      - UP_LOCAL_ADDRESS=up://vehicle/10302/1/0
      - DATABROKER_URI=http://databroker:55555
      - RUST_LOG=info,vehicle_properties=debug
      - MQTT_BROKER_URI=mqtt://mosquitto:1883
      - MQTT_CLIENT_ID=vehicle-properties
      - SPIFFE_ENDPOINT_SOCKET=unix:/tmp/spire-agent/public/api.sock
    depends_on:
      - databroker
      - mosquitto
      - spire-agent
    volumes:
      # the following is needed to talk to the SPIRE Agent's Workload API (via UNIX domain socket)
      - type: volume
        source: spire-agent-socket
        target: /tmp/spire-agent/public
        read_only: false
    command: ["mqtt5"]
  powertrain-mode-controller:
    profiles:
      - powertrain
    image: ghcr.io/eclipse-sdv-blueprints/commercial-sdv-stack/powertrain-mode-controller:latest
    build:
      context: ./uservices
      dockerfile: ./powertrain/Dockerfile
    container_name: powertrain-mode-controller
    networks:
      - vehicle-uprotocol
      - vehicle-sovd
    environment:
      - UP_LOCAL_ADDRESS=up://vehicle/10301/1/0
      - RUST_LOG=info,powertrain=info
      - MQTT_BROKER_URI=mqtt://mosquitto:1883
      - MQTT_CLIENT_ID=powertrain-mode-controller
      - SOVD_SERVER_BASE_URI=http://sovd-cda:20002/vehicle/v15/
      - SOVD_POWERTRAIN_MODE_RESOURCE_PATH=components/blueprint-ecu/data/powertrain_mode
      - SPIFFE_ENDPOINT_SOCKET=unix:/tmp/spire-agent/public/api.sock
    depends_on:
      mosquitto:
        condition: service_healthy
      sovd-cda:
        condition: service_started
    volumes:
      - type: bind
        source: ./config/powertrain-mode-controller
        target: /app/config
        read_only: true
      # the following is needed to talk to the SPIRE Agent's Workload API (via UNIX domain socket)
      - type: volume
        source: spire-agent-socket
        target: /tmp/spire-agent/public
        read_only: false
    command: ["mqtt5"]
  sovd-cda:
    profiles:
      - powertrain
    image: ghcr.io/eclipse-sdv-blueprints/commercial-sdv-stack/opensovd-cda:latest
    build:
      context: ./uservices
      dockerfile: ./cda/Dockerfile
      # these args are necessary in order to satisfy the OpenSOVD cda-main crate's build.rs process
      args:
        - SOURCE_DATE_EPOCH=0
        # the SHA of the git ref we use in uservices/cda/Cargo.toml
        - SOURCE_GIT_SHA=99c60782a6e25f6cff9ba3a3418d0750f936016e
    container_name: cda
    ports:
      - "${CDA_PORT:-20002}:20002"
    volumes:
      - ./config/cda:/app/odx:ro
      # the following is needed to talk to the SPIRE Agent's Workload API (via UNIX domain socket)
      - type: volume
        source: spire-agent-socket
        target: /tmp/spire-agent/public
        read_only: false
    hostname: cda
    networks:
      - vehicle-sovd
    depends_on:
      ecu-sim:
        condition: service_healthy
    environment:
      - RUST_LOG=info
      - SPIFFE_ENDPOINT_SOCKET=unix:/tmp/spire-agent/public/api.sock
    command: ["-d", "/app/odx"]
    restart: unless-stopped
  ecu-sim:
    profiles:
      - powertrain
    image: ghcr.io/eclipse-sdv-blueprints/commercial-sdv-stack/ecu-sim:latest
    build:
      context: ./ecu-sim
      dockerfile: docker/Dockerfile
    ports:
      - "${SIM_CONTROL_PORT:-8181}:8181"
    networks:
      - vehicle-sovd
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8181/ || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
